### ISSUE TITLE
breaks when run with async-io 1.3.0

### ISSUE THREAD

**Issue by johnnyhh** [socketry/async-dns#6]
```
/Users/johnhorne/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-dns-1.0.0/lib/async/dns/server.rb:128:in `block in setup_handlers': undefined method `socket_type' for #<Async::IO::HostEndpoint:0x00007fc535903358> (NoMethodError)
	from /Users/johnhorne/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.3.0/lib/async/io/endpoint.rb:66:in `block in each'
	from /Users/johnhorne/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.3.0/lib/async/io/endpoint.rb:62:in `each'
	from /Users/johnhorne/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.3.0/lib/async/io/endpoint.rb:62:in `each'
	from /Users/johnhorne/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-dns-1.0.0/lib/async/dns/server.rb:127:in `setup_handlers'
	from /Users/johnhorne/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-dns-1.0.0/lib/async/dns/server.rb:109:in `run'
	from /Users/johnhorne/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/rubydns-2.0.1/lib/rubydns.rb:39:in `run_server'
	from ./script/dns/server:19:in `<main>'
```

**Comment by mpdude** [comment]
"thumbs up" means "I'm affected by this as well" :-)

**Comment by ioquatix** [comment]
I'm sorry about this.

There should be updated gems for both `async-io` and `async-dns` which resolve this problem.

I will review the issue and report back.

**Comment by ioquatix** [comment]
It's my fault. My apologies. I prepared but forgot to release `async-dns v1.1.0`. I've now done this and everything is working as expected. Make sure you are using `async-io ~> 1.3` and `async-dns ~> 1.1`.

**Comment by ioquatix** [comment]
By the way, this kind of issue should't happen again as the endpoint API is much more stable now.
